### ISSUE TITLE
Consider adding a license

### ISSUE THREAD

**Issue by Rainyan** [Dennogin/Bonahnsa-Site#5]
Adding a license to the repository could be helpful for encouraging collaboration, and clarifying who owns the copyright to any submitted new/improved content.

### Useful links

* [Choose an open source license](https://choosealicense.com/)
* [GitHub docs: Adding a license to a repository](https://docs.github.com/en/communities/setting-up-your-project-for-healthy-contributions/adding-a-license-to-a-repository)

Some candidate licenses to consider might be the [MIT License](https://choosealicense.com/licenses/mit/), and [GPLv3](https://choosealicense.com/licenses/gpl-3.0/).

**Comment by Dennogin** [comment]
Added an Apache 2.0 License
